fix signed single-bit confusion detected by clang-16
error: implicit truncation from 'int' to a one-bit wide bit-field
changes value from 1 to -1

See also MISRA C:2012, Rule 6.2 "Single-bit named bit fields shall not
be of a signed type":

"According to the C99 Standard Section 6.2.6.2, a single-bit signed
bit-field has a single (one) sign bit and no (zero) value bits. In any
representation of integers, 0 value bits cannot specify a meaningful
value.

A single-bit signed bit-field is therefore unlikely to behave in a
useful way and its presence is likely to indicate programmer confusion."

Signed-off-by: Albrecht Dreß <albrecht.dress@posteo.de>