fix potential buffer overflow detected by clang-16
error: 'sscanf' may overflow; destination buffer in argument 3 has size
256, but the corresponding specifier may require size 257

Signed-off-by: Albrecht Dreß <albrecht.dress@posteo.de>